### ISSUE TITLE
parse out tree metadata to put in relationships table

### ISSUE THREAD

**Issue by jmoseman01** [JohnVCS/fossologyFunTime#16]

**Comment by jmoseman01** [comment]
mvn dependency:tree -DoutputType=graphml -DoutputFile=depmetadata.graphml

this will output the metadata into a parcible format

**Comment by jmoseman01** [comment]
> > > import networkx
> > > networkx.read_graphml("depMeta.graphml")

**Comment by jmoseman01** [comment]
https://pypi.python.org/pypi/pygraphviz

**Comment by jmoseman01** [comment]
https://maven.apache.org/plugins/maven-dependency-plugin/tree-mojo.html

**Comment by jmoseman01** [comment]
mvn dependency:tree -DoutputType=graphml -DoutputFile=test.graphml

**Comment by JohnVCS** [comment]
Jesse, I will work on this one to parse it out. I am getting lost on accessing the dosocs scanner.

**Comment by jmoseman01** [comment]
http://networkx.github.io/#layout-and-drawing

It seems like you actually want to get the info from networkx not pygraphviz

**Comment by jmoseman01** [comment]
http://networkx.readthedocs.org/en/networkx-1.11/reference/readwrite.graphml.html

**Comment by jmoseman01** [comment]
https://networkx.github.io/documentation/latest/tutorial/tutorial.html#directed-graphs

we might want to look into directed graphs and networkx

**Comment by JohnVCS** [comment]
alright we are going with networkx instead of lxml

**Comment by jmoseman01** [comment]
``` python
>>> import matplotlib.pyplot as plt
>>> import networkx
>>> networkx.draw(networkx.read_graphml("test.graphml"))
>>> plt.show()
```

this is how you draw the graph

sudo apt-get install python-matplotlib

**Comment by jmoseman01** [comment]
http://stackoverflow.com/questions/11479624/is-there-a-way-to-guarantee-hierarchical-output-from-networkx

**Comment by jmoseman01** [comment]
http://networkx.readthedocs.org/en/networkx-1.11/_modules/networkx/drawing/nx_agraph.html#read_dot

**Comment by jmoseman01** [comment]
networkx.drawing.nx_agraph.read_dot("depmetadata.dot")

**Comment by jmoseman01** [comment]
``` python
>>> import networkx
>>> import matplotlib.pyplot as plt
>>> networkx.draw(networkx.drawing.nx_agraph.read_dot("depmetadata.dot"))
>>> plt.show()

```

**Comment by jmoseman01** [comment]
https://networkx.github.io/documentation/latest/reference/classes.multidigraph.html#networkx.MultiDiGraph

**Comment by jmoseman01** [comment]
That is for the dot file.

**Comment by jmoseman01** [comment]
https://www.youtube.com/watch?v=we2xFCPkH0Y

John I think you were right about breadth first search

**Comment by jmoseman01** [comment]
It might be sufficient to just persist the edge information as that is what explains the hierarchy...  I'm still thinking on this issue.

**Comment by jmoseman01** [comment]
I'm closing this as we have figured out how to parse the graphml file
