### ISSUE TITLE
figureout what is up with the inconsistency of the tree command for graphml

### ISSUE THREAD

**Issue by jmoseman01** [JohnVCS/fossologyFunTime#18]
mvn dependency:tree -DoutputType=graphml -DoutputFile=test.graphml

**Comment by jmoseman01** [comment]
sometimes it'll give you the right output but sometimes it won't.....

**Comment by jmoseman01** [comment]
try transposing the arguments mvn dependency:tree -DoutputFile=test.graphml -DoutputType=graphml

**Comment by jmoseman01** [comment]
mvn dependency:tree -DoutputFile=happy.graphml -DoutputType=graphml

**Comment by JohnVCS** [comment]
this required Maven 3.3.3 and also make sure -DouputFile comes first then -DoutputType.
