### ISSUE TITLE
Graph traversal/edge persisitence

### ISSUE THREAD

**Issue by jmoseman01** [JohnVCS/fossologyFunTime#19]
Now that we've got a way to put the dependency metadata into a python graph object (Digraph and MultiGraph ).   We'll have debate on the data structure and traversal technique.

The edge information exists.  Does this explain enough about the dependency structure?

Do we need a traversal algorithm similar to DFS (depth first search) or Breadth-First Search (BFS) ?

**Comment by jmoseman01** [comment]
I wrote the code in nodeDict.py.  This python script makes a dictionary out of the node data to map out the id to the package info.  The edges are then traversed and translated with the dictionary and appended to edgeLabels.  edgeLabels contains the edges as the package metadata.  I think this should be sufficient for the relationships table.

**Comment by JohnVCS** [comment]
I'm closing this one because you already figured this one out.
