### ISSUE TITLE
Verify that the edgeLabels(nodeDict.py) list of tupples (edges) is sufficient

### ISSUE THREAD

**Issue by jmoseman01** [JohnVCS/fossologyFunTime#20]
Verify that the edgeLabels(nodeDict.py) list of tupples (edges) is sufficient for the relationship table.  Does it contain all the edges?
Does it contain all the depedencies we care about?
Is there sufficient information?

**Comment by jmoseman01** [comment]
mvn dependency:tree

**Comment by JohnVCS** [comment]
I compared the relationship side by side using two terminals. It's good! This thing is really cool.

**Comment by JohnVCS** [comment]
Left hand side on the output corresponds to the parent, and then the right hand side is the child.

**Comment by JohnVCS** [comment]
Closing since it has been verified.
